### PR TITLE
20200325 updates

### PR DESCRIPTION
**Pull request by hjmjohnson**
Improve continuous integration testing.  See https://my.cdash.org/index.php?project=tclap&date=2020-03-25 for results of CI dashboard builds.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@DAarno  I have added a CI build system to this for improved testing on many different platforms.

**Comment by DAarno** [comment]
FYI, there is also a CI setup for the canonical sourceforge repo: https://dev.azure.com/danielaarno/tclap/_dashboards/dashboard/6896dc4d-6225-481d-a06d-c1f690d561b5

**Comment by hjmjohnson** [comment]
@DAarno What is the process for making pull requests to SourceForge?  I could not find documentation for defining the recommended contribution guide.

**Comment by hjmjohnson** [comment]
@DAarno What is the process for evaluating and accepting/rejecting pull requests?

**Comment by DAarno** [comment]
@hjmjohnson, sorry for delay in reply - it's been a busy week. As for pull requests to SourceForge, https://sourceforge.net/p/forge/documentation/Git/ has some good documentation. I think you wanted to send a merge request, right? If so you can visit https://sourceforge.net/p/tclap/code/ci/1.4-dev/tree/ and click the "Fork" button on the left nav-bar to fork your copy of the repository, apply the changes and then send a merge request from there.

You can also simply send a patch (use git format-patch) if you think that's easier.

As for what changes are accepted, there are a few basic things that need to be true. In general it's good to first file a bug/feature request and discuss whatever you intend/want to do there as it can save some time: https://sourceforge.net/p/tclap/_list/tickets

In general, any patch must do a few things:
1) It must be clear what is being done and why and it must be useful to "general users" of TCLAP
2) Come with reasonable test coverage
3) If it's user visible, be documented with doxy-comment.
4) Complexity to value ratio must be reasonable

This is not an exhaustive list (doesn't exist) but these are the few things that are most likely to trip folks up. The other thing is that changes should most likely go towards 1.4-dev branch at this point as 1.2/master is frozen and should only receive bug fixes (no new features).

Always happy to discuss ideas and contributions, preferably over at https://sourceforge.net/p/tclap/_list/tickets since that leaves a trail of the discussion for anyone else interested in the topic.

**Pull request merged**
